
    <!-- custom js '. data_realisasi .'-->
    <script src="<?php echo base_url('assets/datatables/jquery.dataTables.js') ?>"></script>
    <script src="<?php echo base_url('assets/datatables/dataTables.bootstrap.js') ?>"></script>
    <?php 
    $bidang = $this->session->userdata('userBidang');
    $user_id = $this->session->userdata('user_id');
    //print_r($bidang[0]->name);
    $user_groups = $this->ion_auth->get_users_groups($user_id)->result();
    print_r($user_groups[0]);
    $userBidang = $user_groups[0];
    ?>
    <script type="text/javascript">
        $(document).ready(function() {
            $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
            {
                return {
                    "iStart": oSettings._iDisplayStart,
                    "iEnd": oSettings.fnDisplayEnd(),
                    "iLength": oSettings._iDisplayLength,
                    "iTotal": oSettings.fnRecordsTotal(),
                    "iFilteredTotal": oSettings.fnRecordsDisplay(),
                    "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                    "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
                };
            };

            var t = $("#mytable").dataTable({
                initComplete: function() {
                    var api = this.api();
                    $('#mytable_filter input')
                            .off('.DT')
                            .on('keyup.DT', function(e) {
                                if (e.keyCode == 13) {
                                    api.search(this.value).draw();
                        }
                    });
                },
                oLanguage: {
                    //sProcessing: "loading..."
                    sProcessing: "</div><div class='overlay'>" +
                                        "<i class='fa fa-refresh fa-spin'></i>" +
                                    "</div>"
                },
                processing: true,
                serverSide: true,
                ajax: {"url": "data_realisasi/json", "type": "POST"},
                columns: [
                    {
                        "data": "kdRealisasi",
                        "orderable": false
                    },,
                    {
                        "data" : "action",
                        "orderable": false,
                        "className" : "text-center"
                    }
                ],
                order: [[0, 'desc']],
                rowCallback: function(row, data, iDisplayIndex) {
                    var info = this.fnPagingInfo();
                    var page = info.iPage;
                    var length = info.iLength;
                    var index = page * length + (iDisplayIndex + 1);
                    $('td:eq(0)', row).html(index);
                }
            });
        });
    </script>

    <script type="text/javascript">
        // CODE HERE
        $('#progres').on('change',function () {
           alert();
           $('#nilaiBAP').val(100000);
        });
        <?php $tahunAnggaran = $this->session->userdata('tahun_anggran'); ?>
        $('#noSPPSPM').on('change',function () {
           alert();
           var no = $(this).val();
           var ta = '<?= $tahunAnggaran ?>';
           $('#noSPP').val(no+'/SPP-LS-BM/DPUPR/'+ta);
           $('#noSPM').val(no+'/SPP-LS-BM/DPUPR/'+ta);
        });    
        
        $('#JenisTagihan option:eq(1)').prop('selected', true)

    </script>
    <!-- custom js m_opd-->
    




<?php
/* End of file data_realisasi/custom_js.php */
/* Location: ./application/view/data_realisasi/custom_js.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-28 09:40:54 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 28 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
