<!doctype html>
<html>
    <head>
        <title> <?= _APLIKASI_ ?> | MASTER_PEGAWAI > <?php echo $button ?></title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Master_pegawai <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    <div class="form-group">
            <label for="varchar">Nama <?php echo form_error('nama') ?></label>
            <input type="text" class="form-control" name="nama" id="nama" placeholder="Nama" value="<?php echo $nama; ?>" />
        </div>
	    <div class="form-group">
            <label for="nip">Nip <?php echo form_error('nip') ?></label>
            <textarea class="form-control" rows="3" name="nip" id="nip" placeholder="Nip"><?php echo $nip; ?></textarea>
        </div>
	    <div class="form-group">
            <label for="varchar">Jabatan <?php echo form_error('jabatan') ?></label>
            <input type="text" class="form-control" name="jabatan" id="jabatan" placeholder="Jabatan" value="<?php echo $jabatan; ?>" />
        </div>
	    <div class="form-group">
            <label for="pendidikan">Pendidikan <?php echo form_error('pendidikan') ?></label>
            <textarea class="form-control" rows="3" name="pendidikan" id="pendidikan" placeholder="Pendidikan"><?php echo $pendidikan; ?></textarea>
        </div>
	    <div class="form-group">
            <label for="jurusan">Jurusan <?php echo form_error('jurusan') ?></label>
            <textarea class="form-control" rows="3" name="jurusan" id="jurusan" placeholder="Jurusan"><?php echo $jurusan; ?></textarea>
        </div>
	    <div class="form-group">
            <label for="varchar">Pangkat <?php echo form_error('pangkat') ?></label>
            <input type="text" class="form-control" name="pangkat" id="pangkat" placeholder="Pangkat" value="<?php echo $pangkat; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Golongan <?php echo form_error('golongan') ?></label>
            <input type="text" class="form-control" name="golongan" id="golongan" placeholder="Golongan" value="<?php echo $golongan; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Ruang <?php echo form_error('ruang') ?></label>
            <input type="text" class="form-control" name="ruang" id="ruang" placeholder="Ruang" value="<?php echo $ruang; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Tempat <?php echo form_error('tempat') ?></label>
            <input type="text" class="form-control" name="tempat" id="tempat" placeholder="Tempat" value="<?php echo $tempat; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tanggal Lahir <?php echo form_error('tanggal_lahir') ?></label>
            <input type="text" class="form-control" name="tanggal_lahir" id="tanggal_lahir" placeholder="Tanggal Lahir" value="<?php echo $tanggal_lahir; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tgl Aktif <?php echo form_error('tgl_aktif') ?></label>
            <input type="text" class="form-control" name="tgl_aktif" id="tgl_aktif" placeholder="Tgl Aktif" value="<?php echo $tgl_aktif; ?>" />
        </div>
	    <div class="form-group">
            <label for="set">Status <?php echo form_error('status') ?></label>
            <input type="text" class="form-control" name="status" id="status" placeholder="Status" value="<?php echo $status; ?>" />
        </div>
	    <div class="form-group">
            <label for="datetime">Date Update <?php echo form_error('date_update') ?></label>
            <input type="text" class="form-control" name="date_update" id="date_update" placeholder="Date Update" value="<?php echo $date_update; ?>" />
        </div>
	    <input type="hidden" name="id_peg" value="<?php echo $id_peg; ?>" /> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('master_pegawai') ?>" class="btn btn-default">Cancel</a>
	</form>
    </body>
</html>




<?php
/* End of file master_pegawai/master_pegawai_form */
/* Location: ./application/view/master_pegawai/master_pegawai_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-20 21:38:38 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 20 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
