<!doctype html>
<html>
    <head>
        <title> <?= _APLIKASI_ ?> | PAJAK > <?php echo $button ?></title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Pajak <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    <div class="form-group">
            <label for="varchar">Pasal <?php echo form_error('pasal') ?></label>
            <input type="text" class="form-control" name="pasal" id="pasal" placeholder="Pasal" value="<?php echo $pasal; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Jenis <?php echo form_error('jenis') ?></label>
            <input type="text" class="form-control" name="jenis" id="jenis" placeholder="Jenis" value="<?php echo $jenis; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Kegiatan <?php echo form_error('kegiatan') ?></label>
            <input type="text" class="form-control" name="kegiatan" id="kegiatan" placeholder="Kegiatan" value="<?php echo $kegiatan; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">JenisKegiatan <?php echo form_error('jenisKegiatan') ?></label>
            <input type="text" class="form-control" name="jenisKegiatan" id="jenisKegiatan" placeholder="JenisKegiatan" value="<?php echo $jenisKegiatan; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Kualifikasi <?php echo form_error('kualifikasi') ?></label>
            <input type="text" class="form-control" name="kualifikasi" id="kualifikasi" placeholder="Kualifikasi" value="<?php echo $kualifikasi; ?>" />
        </div>
	    <div class="form-group">
            <label for="double">Potongan <?php echo form_error('potongan') ?></label>
            <input type="text" class="form-control" name="potongan" id="potongan" placeholder="Potongan" value="<?php echo $potongan; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Ket <?php echo form_error('ket') ?></label>
            <input type="text" class="form-control" name="ket" id="ket" placeholder="Ket" value="<?php echo $ket; ?>" />
        </div>
	    <input type="hidden" name="id" value="<?php echo $id; ?>" /> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('pajak') ?>" class="btn btn-default">Cancel</a>
	</form>
    </body>
</html>




<?php
/* End of file pajak/pajak_form */
/* Location: ./application/view/pajak/pajak_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 17:27:29 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
