<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Pajak List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Pasal</th>
		<th>Jenis</th>
		<th>Kegiatan</th>
		<th>JenisKegiatan</th>
		<th>Kualifikasi</th>
		<th>Potongan</th>
		<th>Ket</th>
		
            </tr><?php
            foreach ($pajak_data as $pajak)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $pajak->pasal ?></td>
		      <td><?php echo $pajak->jenis ?></td>
		      <td><?php echo $pajak->kegiatan ?></td>
		      <td><?php echo $pajak->jenisKegiatan ?></td>
		      <td><?php echo $pajak->kualifikasi ?></td>
		      <td><?php echo $pajak->potongan ?></td>
		      <td><?php echo $pajak->ket ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file pajak/pajak_pdf */
/* Location: ./application/views/pajak/pajak_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 17:27:30 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
