<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Pajak Read</h2>
        <table class="table">
	    <tr><td>Pasal</td><td><?php echo $pasal; ?></td></tr>
	    <tr><td>Jenis</td><td><?php echo $jenis; ?></td></tr>
	    <tr><td>Kegiatan</td><td><?php echo $kegiatan; ?></td></tr>
	    <tr><td>JenisKegiatan</td><td><?php echo $jenisKegiatan; ?></td></tr>
	    <tr><td>Kualifikasi</td><td><?php echo $kualifikasi; ?></td></tr>
	    <tr><td>Potongan</td><td><?php echo $potongan; ?></td></tr>
	    <tr><td>Ket</td><td><?php echo $ket; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('pajak') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file pajak/pajak_read */
/* Location: ./application/views/pajak/pajak_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 17:27:29 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
