<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Simda List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>COL1</th>
		<th>COL2</th>
		<th>COL3</th>
		<th>COL4</th>
		<th>COL5</th>
		<th>COL6</th>
		<th>COL7</th>
		<th>COL8</th>
		<th>COL9</th>
		<th>COL10</th>
		<th>COL11</th>
		<th>COL12</th>
		<th>COL13</th>
		<th>COL14</th>
		<th>COL15</th>
		<th>COL16</th>
		<th>COL17</th>
		<th>COL18</th>
		<th>COL19</th>
		<th>COL20</th>
		<th>COL21</th>
		<th>COL22</th>
		<th>COL23</th>
		<th>COL24</th>
		<th>COL25</th>
		<th>COL26</th>
		<th>COL27</th>
		<th>COL28</th>
		<th>COL29</th>
		<th>COL30</th>
		<th>COL31</th>
		<th>COL32</th>
		<th>COL33</th>
		<th>COL34</th>
		<th>COL35</th>
		<th>COL36</th>
		<th>COL37</th>
		<th>COL38</th>
		<th>COL39</th>
		<th>COL40</th>
		<th>TglDPA</th>
		<th>NoDPA</th>
		
            </tr><?php
            foreach ($simda_test_data as $simda_test)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $simda_test->COL1 ?></td>
		      <td><?php echo $simda_test->COL2 ?></td>
		      <td><?php echo $simda_test->COL3 ?></td>
		      <td><?php echo $simda_test->COL4 ?></td>
		      <td><?php echo $simda_test->COL5 ?></td>
		      <td><?php echo $simda_test->COL6 ?></td>
		      <td><?php echo $simda_test->COL7 ?></td>
		      <td><?php echo $simda_test->COL8 ?></td>
		      <td><?php echo $simda_test->COL9 ?></td>
		      <td><?php echo $simda_test->COL10 ?></td>
		      <td><?php echo $simda_test->COL11 ?></td>
		      <td><?php echo $simda_test->COL12 ?></td>
		      <td><?php echo $simda_test->COL13 ?></td>
		      <td><?php echo $simda_test->COL14 ?></td>
		      <td><?php echo $simda_test->COL15 ?></td>
		      <td><?php echo $simda_test->COL16 ?></td>
		      <td><?php echo $simda_test->COL17 ?></td>
		      <td><?php echo $simda_test->COL18 ?></td>
		      <td><?php echo $simda_test->COL19 ?></td>
		      <td><?php echo $simda_test->COL20 ?></td>
		      <td><?php echo $simda_test->COL21 ?></td>
		      <td><?php echo $simda_test->COL22 ?></td>
		      <td><?php echo $simda_test->COL23 ?></td>
		      <td><?php echo $simda_test->COL24 ?></td>
		      <td><?php echo $simda_test->COL25 ?></td>
		      <td><?php echo $simda_test->COL26 ?></td>
		      <td><?php echo $simda_test->COL27 ?></td>
		      <td><?php echo $simda_test->COL28 ?></td>
		      <td><?php echo $simda_test->COL29 ?></td>
		      <td><?php echo $simda_test->COL30 ?></td>
		      <td><?php echo $simda_test->COL31 ?></td>
		      <td><?php echo $simda_test->COL32 ?></td>
		      <td><?php echo $simda_test->COL33 ?></td>
		      <td><?php echo $simda_test->COL34 ?></td>
		      <td><?php echo $simda_test->COL35 ?></td>
		      <td><?php echo $simda_test->COL36 ?></td>
		      <td><?php echo $simda_test->COL37 ?></td>
		      <td><?php echo $simda_test->COL38 ?></td>
		      <td><?php echo $simda_test->COL39 ?></td>
		      <td><?php echo $simda_test->COL40 ?></td>
		      <td><?php echo $simda_test->tglDPA ?></td>
		      <td><?php echo $simda_test->noDPA ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file simda/simda_pdf */
/* Location: ./application/views/simda/simda_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 04:56:22 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
