<!doctype html>
<html>
    <head>
        <title> <?= _APLIKASI_ ?> | TBPAKET > <?php echo $button ?></title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Tbpaket <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    <div class="form-group">
            <label for="nmPaket">NmPaket <?php echo form_error('nmPaket') ?></label>
            <textarea class="form-control" rows="3" name="nmPaket" id="nmPaket" placeholder="NmPaket"><?php echo $nmPaket; ?></textarea>
        </div>
	    <div class="form-group">
            <label for="year">Tahun <?php echo form_error('tahun') ?></label>
            <input type="text" class="form-control" name="tahun" id="tahun" placeholder="Tahun" value="<?php echo $tahun; ?>" />
        </div>
	    <div class="form-group">
            <label for="md5namatahun">Md5namatahun <?php echo form_error('md5namatahun') ?></label>
            <textarea class="form-control" rows="3" name="md5namatahun" id="md5namatahun" placeholder="Md5namatahun"><?php echo $md5namatahun; ?></textarea>
        </div>
	    <div class="form-group">
            <label for="varchar">Bidang <?php echo form_error('bidang') ?></label>
            <input type="text" class="form-control" name="bidang" id="bidang" placeholder="Bidang" value="<?php echo $bidang; ?>" />
        </div>
	    <input type="hidden" name="kdPaket" value="<?php echo $kdPaket; ?>" /> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('tbpaket') ?>" class="btn btn-default">Cancel</a>
	</form>
    </body>
</html>




<?php
/* End of file tbpaket/tbpaket_form */
/* Location: ./application/view/tbpaket/tbpaket_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:19:04 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
