<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Tbpaket Read</h2>
        <table class="table">
	    <tr><td>NmPaket</td><td><?php echo $nmPaket; ?></td></tr>
	    <tr><td>Tahun</td><td><?php echo $tahun; ?></td></tr>
	    <tr><td>Md5namatahun</td><td><?php echo $md5namatahun; ?></td></tr>
	    <tr><td>Bidang</td><td><?php echo $bidang; ?></td></tr>

        
	    <tr><td></td><td><a href="<?php echo site_url('tbpaket') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file tbpaket/tbpaket_read */
/* Location: ./application/views/tbpaket/tbpaket_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:19:04 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
