
<section class="content-header">
    <h1>
        Halaman Paket 
        <small> Daftar Paket yang telah dikotrak </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?= base_url('paket')?>">Paket</a></li>
        <li class="active"><?= $this->uri->segment(2)?></li>
    </ol>
</section>

<script>
function konfirmasiDelete(data) {    
var konfirm = confirm('Saya akan menghapus data \n' +data);    
if(konfirm==true){
    var hapus = prompt("Semua data (kontrak, pejabat, jaminan, perusahan dan realisasi) pada paket ini akan dihapus \n Konfirmasi menghapus data \n "+data+" ? \n Ketik:\n 'yakin' untuk lanjut hapus", "");
    if (hapus == 'yakin') {
            return true;
    }else{
        alert('Anda Tidak yakin ! \n Proses pengapusan kami batalkan.');
        return false;
    }
}else{
    return false;
}
}
</script>



<?php
/* End of file tbpaket/inc_header.php */
/* Location: ./application/views/tbpaket/inc_header.php*/
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:20:41 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
