<h2 style="margin-top:0px">Paket <?php echo $button ?></h2>
<form action="<?php echo $action; ?>" method="post">
    <!--select class="form-control js-data-example-ajax"></select-->

    <div class="form-group">
        <label for="nmPaket">Nama Pekerjaan <?php echo form_error('kdPekerjaan') ?></label>
        <select class="form-control js-data-simda-ajax" style="width: 100%;" rows="1" name="kdPekerjaan"
            id="kdPekerjaan" placeholder="Pekerjaan">

        </select>

        <!--select class="form-control select2" rows="3" name="Pekerjaan" id="Pekerjaan" placeholder="Pekerjaan">
                <?php
                /*
                $simda = $this->db->get_where('simda',['COL10'=>'Belanja Modal','COL39'=>'Pekerjaan Umum dan Penataan Ruang']);
                foreach ($simda->result_array() as $p) {
                    echo '
                    <option value="'.$p['No'].'">'.$p['COL30'].'</option>
                    ';
                }
                */
                ?>

            </select-->
        <?php 
            //print_r($simda->result()); 
            ?>
    </div>
    <div class="alert alert-info" id="info-paket" style="display:none">
    <p id="ruasTitle"></p>
    <ol id="ruasPekerjaan"></ol>
    </div>
    <!--div id="result">sss</div>

    <a class="btn" id="addBtn">addBtn</a>

    <ul class="select2-selection__rendered">
        <li class="select2-selection__choice" title=" Pembangunan Jalan Batang Tian - Padang Langkuang">
            <span class="select2-selection__choice__remove" role="presentation">×</span></li>
        <li class="select2-selection__choice" title=" Pembangunan Jalan Paraman Sawah - Kampung Pinang">
            <span  class="select2-selection__choice__remove" role="presentation">×</span></li>
        <li class="select2-search select2-search--inline"><input class="select2-search__field" type="search"
                tabindex="-1" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"
                role="textbox" placeholder="" style="width: 0.75em;"></li>
    </ul-->



    <div class="form-group">
        <label for="nmPaket">Nama Paket <small class="text-aqua">Biasanya sama dengan nama pekerjaan</small><?php echo form_error('nmPaket') ?></label>
        <textarea class="form-control select2-setText" rows="3" name="nmPaket" id="nmPaket" readonly
            placeholder="Nama paket biasanya sama dengan nama pekerjaan"><?php echo $nmPaket; ?></textarea>
    </div>
    <div class="form-group">
        <label for="year">Tahun <?php echo form_error('tahun') ?></label>
        <input type="year" class="form-control datepicker-year" name="tahun" id="tahun" placeholder="Tahun Pelaksanaan"
            value="<?php echo $tahun; ?>" />
    </div>
    <div class="form-group hide">
            <label for="md5namatahun">Md5namatahun <?php echo form_error('md5namatahun') ?></label>
            <textarea class="form-control" rows="3" name="md5namatahun" id="md5namatahun" placeholder="Md5namatahun"><?php echo $md5namatahun; ?></textarea>
        </div>
    <div class="form-group">
        <label for="varchar">Bidang <?php echo form_error('bidang') ?></label>
        <select type="text" class="form-control" name="bidang" id="bidang" placeholder="Bidang"
            value="<?php echo $bidang; ?>">
            <?php 
                $group = $this->db->get_where('groups',['id  > '=> '3']);
            ?>
            <option value="<?php echo $bidang; ?>">
                <?php echo $this->db->get_where('groups',['id'=>$bidang])->row('name'); ?></option>
            <?php
                
                foreach ($group->result_array() as $g) {
                    echo '
                    <option value="'.$g['id'].'">[ '.$g['name'].' ] - '.$g['description'].'</option>
                    ';
                }
            ?>
        </select>

    </div>
    <input type="hidden" name="kdPaket" value="<?php echo $kdPaket; ?>" />
    <a href="<?php echo site_url('paket') ?>" class="btn btn-danger pull-right"><i class="fa fa-arrow-left"></i> Kembali</a>
    <button type="submit" class="btn btn-primary"><i class="fa fa-pencil"></i> <?php echo $button ?></button>
    
</form>




<?php
/* End of file tbpaket/tbpaket_form */
/* Location: ./application/view/tbpaket/tbpaket_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:20:41 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>