
        <?php
        $kdKontrak = $this->uri->segment(3);
        $row = $this->Data_kontrak_model->get_by_id($kdKontrak);
        ?>
        <h2 style="margin-top:0px"> Data Kontrak : <?php echo $row->nomorKontrak ?></h2>
<!--DETAIL KONTRAK-->

<?php

//echo  $this->db->last_query();
//print_r($row);
    echo'
    <table class="table table-striped table-hover">
        <tbody>
            <tr>
                <th width="15%">Nomor Kontrak</th>
                <td>: '.$row->nomorKontrak.'</td>
            </tr>
            <tr>
                <th>Tanggal Kontrak</th>
                <td>: '.$row->TglKontrak.'</td>
            </tr>
            <tr>
                <th>Tanggal Akhir</th>
                <td>: '.$row->tglakhir.'</td>
            </tr>
            <tr>
                <th>Nilai Kontrak</th>
                <td>: '.$row->nilaiKontrak.'</td>
            </tr>
        </tbody>
    </table>';
?>
<hr>
<h3>Daftar Addendum</h3>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Nomor </th>
            <th>Tanggal </th>
            <th>Akhir </th>
            <th>Nilai </th>
        </tr>
    </thead>
    <tbody>
    <?php
       $addendum = $this->db->get_where('data_kontrak_addendum',['kdKontrak' => $this->uri->segment(3)]);
        foreach ($addendum->result_array() as $add) {
            echo '<tr>
                    <td>'.$add['nomorAddendum'].'</td>
                    <td>'.$add['Tgl'].'</td>
                    <td>'.$add['tglakhir'].'</td>
                    <td>'.$add['nilai'].'</td>
                  </tr>';
        }
        //echo $this->uri->segment(3);
        //print_r($addendum->result_array());
    ?>
        <!--tr>
            <td>000</td>
            <td>000</td>
            <td>000</td>
            <td>000</td>
        </tr-->
    </tbody>
</table>
<hr>

<h3 style="margin-top:0px"><small>Tambah Data addendum untuk Nomor Kontrak:</small><br/> 
<b class="text-danger"><?php echo $row->nomorKontrak ?></b></h3>
        <form action="<?php echo $action; ?>" method="post">
        <div class="form-group" style="display: none;">
            <label for="varchar">Nomor Kontrak <?php echo $kdKontrak; ?><?php echo form_error('kdKontrak') ?></label>
            <input type="hidden" class="form-control" autocomplete="off" name="kdKontrak" id="kdKontrak" placeholder="KdKontrak" value="<?php echo $kdKontrak; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Nomor Addendum <?php echo form_error('kdAddendum') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="kdAddendum" id="kdAddendum" placeholder="Nomor Addendum" value="<?php echo $kdAddendum; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tanggal Addendum <?php echo form_error('Tgl') ?></label>
            <input type="text" class="form-control datepicker" autocomplete="off" name="Tgl" id="Tgl" placeholder="Tanggal" value="<?php echo $Tgl; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tanggal Akhir Addendum <?php echo form_error('tglakhir') ?></label>
            <input type="text" class="form-control datepicker" autocomplete="off" name="tglakhir" id="tglakhir" placeholder="Tanggal Akhir" value="<?php echo $tglakhir; ?>" />
        </div>
        <div class="form-group">
            <label for="double">Nilai Addendum <?php echo form_error('nilai') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="nilai" id="nilai" placeholder="Nilai Addendum" value="<?php echo $nilai; ?>" />
        </div>
        <div class="form-group">
            <label for="double">Nilai Addendum <?php echo form_error('nilai') ?></label>
            <div class="checkbox">
                      <label class="text-blue">
                        <input type="checkbox" required> Data yang diisi sudah benar.
                      </label>
                    </div>
        
        </div>
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('paket/read/'.$row->kdpaket) ?>" class="btn btn-danger pull-right"> <i class="fa fa-arrow-left"></i> Kembali</a>
	</form>
    




<?php
/* End of file data_kontrak_addendum/data_kontrak_addendum_form */
/* Location: ./application/view/data_kontrak_addendum/data_kontrak_addendum_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:59:52 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
