<!doctype html>
<html>
    <head>
        <title> <?= _APLIKASI_ ?> | MASTER_DPA2 > <?php echo $button ?></title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Master_dpa <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    <div class="form-group">
            <label for="year">Tahun <?php echo form_error('tahun') ?></label>
            <input type="text" class="form-control" name="tahun" id="tahun" placeholder="Tahun" value="<?php echo $tahun; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tanggal <?php echo form_error('Tanggal') ?></label>
            <input type="text" class="form-control" name="Tanggal" id="Tanggal" placeholder="Tanggal" value="<?php echo $Tanggal; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Pa Id <?php echo form_error('pa_id') ?></label>
            <input type="text" class="form-control" name="pa_id" id="pa_id" placeholder="Pa Id" value="<?php echo $pa_id; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Bendahara Id <?php echo form_error('bendahara_id') ?></label>
            <input type="text" class="form-control" name="bendahara_id" id="bendahara_id" placeholder="Bendahara Id" value="<?php echo $bendahara_id; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Ppk Id <?php echo form_error('ppk_id') ?></label>
            <input type="text" class="form-control" name="ppk_id" id="ppk_id" placeholder="Ppk Id" value="<?php echo $ppk_id; ?>" />
        </div>
	    <input type="hidden" name="kdDPA" value="<?php echo $kdDPA; ?>" /> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('master_dpa2') ?>" class="btn btn-default">Cancel</a>
	</form>
    </body>
</html>




<?php
/* End of file master_dpa/master_dpa_form */
/* Location: ./application/view/master_dpa/master_dpa_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-17 00:55:46 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 17 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
