<div class="row">

<div class="col-md-12">
    <h2 style="margin-top:0px"> Detail Data kontrak</h2>
</div>    
    <div class="col-md-6">
    <h3 style="margin-top:0px">Kontrak</h3>   
    <table class="table">
	    <tr><th width="25%">id</th><td><small><?php echo $kdKontrak; ?></small></td></tr>
	    <tr><th >Nomor Kontrak</th><td><?php echo $nomorKontrak; ?></td></tr>
        <tr><th>Tanggal Kontrak</th><td><?php echo $TglKontrak; ?></td></tr>
        <tr><th>Tanggal akhir</th><td><?php echo $tglakhir; ?></td></tr>
        <tr><th>Paket</th><td><?php echo $namapaket; ?></td></tr>
        <tr><td><a href="<?php echo site_url('paket/read/'.$kdpaket) ?>" class="btn btn-xs btn-danger"><i class="fa fa-arrow-left"></i>    Kembali</a></td><td></td></tr>
    </table>
    </div>
    <div class="col-md-6">
    <h3 style="margin-top:0px">Info</h3>    
    <table class="table">    
	    <tr><th width="25%">Nomor PHO</th><td><?php echo $NomorPHO; ?></td></tr>
	    <tr><th>Tgl PHO</th><td><?php echo $tglPHO; ?></td></tr>
	    <tr><th>Nomor FHO</th><td><?php echo $NomorFHO; ?></td></tr>
	    <tr><th>Tgl FHO</th><td><?php echo $tglFHO; ?></td></tr>
	    <tr><th>Nilai Kontrak</th><td><?php echo $nilaiKontrak; ?></td></tr>
	</table>
    </div>
    <hr>
<div class="col-md-12">    
<h3 style="margin-top:0px">Data kontrak Addendum <a href="<?php echo site_url('data_kontrak_addendum/kontrak/'.$kdKontrak) ?>" class="btn btn-xs btn-primary">+ Addendum</a></h3>
<?php 
$addendum = $this->Data_kontrak_model->get_addendum_by_idkontrak($kdKontrak);
//print_r($addendum);
?>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Nomor Addendum</th>
            <th>Tanggal Addendum</th>
            <th>Tanggal Akhir</th>
            <th>Nilai</th>
            <th>Aksi</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach ($addendum as $add) {
    ?>
        <tr>
            <!--td><?= $add['kdAddendum']; ?></td-->
            <td><?= $add['nomorAddendum']; ?></td>
            <td><?= $add['Tgl']; ?></td>
            <td><?= $add['tglakhir']; ?></td>
            <td><?= $add['nilai']; ?></td>
            <td>
                <a href="<?php echo site_url('data_kontrak') ?>" class="btn btn-xs btn-warning">Edit</a>
                <a href="<?php echo site_url('data_kontrak/deleteAddendum/'.$add['kdAddendum'].'/'.$kdKontrak) ?>" class="btn btn-xs btn-danger">Hapus</a>
            </td>
        </tr>
    <?php
    }
    ?>    
    </tbody>
</table>
</div>
</div>

<?php
/* End of file data_kontrak/data_kontrak_read */
/* Location: ./application/views/data_kontrak/data_kontrak_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:59:44 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
