<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Data_kontrak List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Tglakhir</th>
		<th>TglKontrak</th>
		<th>NomorPHO</th>
		<th>TglPHO</th>
		<th>NomorFHO</th>
		<th>TglFHO</th>
		<th>NilaiKontrak</th>
		<th>Kdpaket</th>
		
            </tr><?php
            foreach ($data_kontrak_data as $data_kontrak)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $data_kontrak->tglakhir ?></td>
		      <td><?php echo $data_kontrak->TglKontrak ?></td>
		      <td><?php echo $data_kontrak->NomorPHO ?></td>
		      <td><?php echo $data_kontrak->tglPHO ?></td>
		      <td><?php echo $data_kontrak->NomorFHO ?></td>
		      <td><?php echo $data_kontrak->tglFHO ?></td>
		      <td><?php echo $data_kontrak->nilaiKontrak ?></td>
		      <td><?php echo $data_kontrak->kdpaket ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file data_kontrak/data_kontrak_pdf */
/* Location: ./application/views/data_kontrak/data_kontrak_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:59:44 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
