<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Data_pejabat List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Nipkpa</th>
		<th>Pptk</th>
		<th>Nippptk</th>
		<th>Pengawas</th>
		<th>Nippengawas</th>
		<th>Kdpaket</th>
		
            </tr><?php
            foreach ($data_pejabat_data as $data_pejabat)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $data_pejabat->nipkpa ?></td>
		      <td><?php echo $data_pejabat->pptk ?></td>
		      <td><?php echo $data_pejabat->nippptk ?></td>
		      <td><?php echo $data_pejabat->pengawas ?></td>
		      <td><?php echo $data_pejabat->nippengawas ?></td>
		      <td><?php echo $data_pejabat->kdpaket ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file data_pejabat/data_pejabat_pdf */
/* Location: ./application/views/data_pejabat/data_pejabat_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 19:30:19 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
