<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Data_pejabat Read</h2>
        <table class="table">
	    <tr><td>Nipkpa</td><td><?php echo $nipkpa; ?></td></tr>
	    <tr><td>Pptk</td><td><?php echo $pptk; ?></td></tr>
	    <tr><td>Nippptk</td><td><?php echo $nippptk; ?></td></tr>
	    <tr><td>Pengawas</td><td><?php echo $pengawas; ?></td></tr>
	    <tr><td>Nippengawas</td><td><?php echo $nippengawas; ?></td></tr>
	    <tr><td>Kdpaket</td><td><?php echo $kdpaket; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('data_pejabat') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file data_pejabat/data_pejabat_read */
/* Location: ./application/views/data_pejabat/data_pejabat_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 19:30:19 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
