<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Data_realisasi List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Ke</th>
		<th>Progres</th>
		<th>Fisik</th>
		<th>PotMCLALU</th>
		<th>PotUMK</th>
		<th>PotRETENSI</th>
		<th>NilaiBAP</th>
		<th>PajakPPH</th>
		<th>PajakPPN</th>
		<th>NoSPP</th>
		<th>TglSPP</th>
		<th>NoSPM</th>
		<th>TglSPM</th>
		<th>JenisTagihan</th>
		<th>TglTAGIHAN</th>
		<th>NoTAGIHAN</th>
		<th>Kdpaket</th>
		
            </tr><?php
            foreach ($data_realisasi_test_data as $data_realisasi_test)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $data_realisasi_test->ke ?></td>
		      <td><?php echo $data_realisasi_test->progres ?></td>
		      <td><?php echo $data_realisasi_test->fisik ?></td>
		      <td><?php echo $data_realisasi_test->potMCLALU ?></td>
		      <td><?php echo $data_realisasi_test->potUMK ?></td>
		      <td><?php echo $data_realisasi_test->potRETENSI ?></td>
		      <td><?php echo $data_realisasi_test->nilaiBAP ?></td>
		      <td><?php echo $data_realisasi_test->pajakPPH ?></td>
		      <td><?php echo $data_realisasi_test->pajakPPN ?></td>
		      <td><?php echo $data_realisasi_test->noSPP ?></td>
		      <td><?php echo $data_realisasi_test->tglSPP ?></td>
		      <td><?php echo $data_realisasi_test->noSPM ?></td>
		      <td><?php echo $data_realisasi_test->tglSPM ?></td>
		      <td><?php echo $data_realisasi_test->JenisTagihan ?></td>
		      <td><?php echo $data_realisasi_test->tglTAGIHAN ?></td>
		      <td><?php echo $data_realisasi_test->noTAGIHAN ?></td>
		      <td><?php echo $data_realisasi_test->kdpaket ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file data_realisasi/data_realisasi_pdf */
/* Location: ./application/views/data_realisasi/data_realisasi_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-03 15:55:55 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 03 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
