<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Data_realisasi Read</h2>
        <table class="table">
	    <tr><td>Ke</td><td><?php echo $ke; ?></td></tr>
	    <tr><td>Progres</td><td><?php echo $progres; ?></td></tr>
	    <tr><td>Fisik</td><td><?php echo $fisik; ?></td></tr>
	    <tr><td>PotMCLALU</td><td><?php echo $potMCLALU; ?></td></tr>
	    <tr><td>PotUMK</td><td><?php echo $potUMK; ?></td></tr>
	    <tr><td>PotRETENSI</td><td><?php echo $potRETENSI; ?></td></tr>
	    <tr><td>NilaiBAP</td><td><?php echo $nilaiBAP; ?></td></tr>
	    <tr><td>PajakPPH</td><td><?php echo $pajakPPH; ?></td></tr>
	    <tr><td>PajakPPN</td><td><?php echo $pajakPPN; ?></td></tr>
	    <tr><td>NoSPP</td><td><?php echo $noSPP; ?></td></tr>
	    <tr><td>TglSPP</td><td><?php echo $tglSPP; ?></td></tr>
	    <tr><td>NoSPM</td><td><?php echo $noSPM; ?></td></tr>
	    <tr><td>TglSPM</td><td><?php echo $tglSPM; ?></td></tr>
	    <tr><td>JenisTagihan</td><td><?php echo $JenisTagihan; ?></td></tr>
	    <tr><td>TglTAGIHAN</td><td><?php echo $tglTAGIHAN; ?></td></tr>
	    <tr><td>NoTAGIHAN</td><td><?php echo $noTAGIHAN; ?></td></tr>
	    <tr><td>Kdpaket</td><td><?php echo $kdpaket; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('data_realisasi_test') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file data_realisasi/data_realisasi_read */
/* Location: ./application/views/data_realisasi/data_realisasi_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-03 15:55:55 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 03 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
