<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Master_dpa Read</h2>
        <table class="table">
	    <tr><td>Kategori</td><td><?php echo $kategori; ?></td></tr>
	    <tr><td>Tahun</td><td><?php echo $tahun; ?></td></tr>
	    <tr><td>Tanggal</td><td><?php echo $Tanggal; ?></td></tr>
	    <tr><td>Pa Id</td><td><?php echo $pa_id; ?></td></tr>
	    <tr><td>Bendahara Id</td><td><?php echo $bendahara_id; ?></td></tr>
	    <tr><td>Ppk Id</td><td><?php echo $ppk_id; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('master_dpa') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file master_dpa/master_dpa_read */
/* Location: ./application/views/master_dpa/master_dpa_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-04 00:01:37 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 04 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
