<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Master_dpa List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Kategori</th>
		<th>Tahun</th>
		<th>Tanggal</th>
		<th>Pa Id</th>
		<th>Bendahara Id</th>
		<th>Ppk Id</th>
		
            </tr><?php
            foreach ($master_dpa_data as $master_dpa)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $master_dpa->kategori ?></td>
		      <td><?php echo $master_dpa->tahun ?></td>
		      <td><?php echo $master_dpa->Tanggal ?></td>
		      <td><?php echo $master_dpa->pa_id ?></td>
		      <td><?php echo $master_dpa->bendahara_id ?></td>
		      <td><?php echo $master_dpa->ppk_id ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file master_dpa/master_dpa_pdf */
/* Location: ./application/views/master_dpa/master_dpa_pdf */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-04 00:01:37 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 04 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
