
<section class="content-header">
    <h1>
        Simda 
        <small> simda_form </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
    </ol>
</section>


<style>
td.details-control {
    background: url('<?= base_url('assets/datatables/images')?>/details_open.png') no-repeat center center;
    cursor: pointer;
}
tr.details td.details-control {
    background: url('<?= base_url('assets/datatables/images/')?>details_close.png') no-repeat center center;
}
</style>


<?php
/* End of file simda/inc_header.php */
/* Location: ./application/views/simda/inc_header.php*/
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-18 21:02:06 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 18 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
