<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Simda Read</h2>
        <table class="table">
	    <tr><td>COL1</td><td><?php echo $COL1; ?></td></tr>
	    <tr><td>COL2</td><td><?php echo $COL2; ?></td></tr>
	    <tr><td>COL3</td><td><?php echo $COL3; ?></td></tr>
	    <tr><td>COL4</td><td><?php echo $COL4; ?></td></tr>
	    <tr><td>COL5</td><td><?php echo $COL5; ?></td></tr>
	    <tr><td>COL6</td><td><?php echo $COL6; ?></td></tr>
	    <tr><td>COL7</td><td><?php echo $COL7; ?></td></tr>
	    <tr><td>COL8</td><td><?php echo $COL8; ?></td></tr>
	    <tr><td>COL9</td><td><?php echo $COL9; ?></td></tr>
	    <tr><td>COL10</td><td><?php echo $COL10; ?></td></tr>
	    <tr><td>COL11</td><td><?php echo $COL11; ?></td></tr>
	    <tr><td>COL12</td><td><?php echo $COL12; ?></td></tr>
	    <tr><td>COL13</td><td><?php echo $COL13; ?></td></tr>
	    <tr><td>COL14</td><td><?php echo $COL14; ?></td></tr>
	    <tr><td>COL15</td><td><?php echo $COL15; ?></td></tr>
	    <tr><td>COL16</td><td><?php echo $COL16; ?></td></tr>
	    <tr><td>COL17</td><td><?php echo $COL17; ?></td></tr>
	    <tr><td>COL18</td><td><?php echo $COL18; ?></td></tr>
	    <tr><td>COL19</td><td><?php echo $COL19; ?></td></tr>
	    <tr><td>COL20</td><td><?php echo $COL20; ?></td></tr>
	    <tr><td>COL21</td><td><?php echo $COL21; ?></td></tr>
	    <tr><td>COL22</td><td><?php echo $COL22; ?></td></tr>
	    <tr><td>COL23</td><td><?php echo $COL23; ?></td></tr>
	    <tr><td>COL24</td><td><?php echo $COL24; ?></td></tr>
	    <tr><td>COL25</td><td><?php echo $COL25; ?></td></tr>
	    <tr><td>COL26</td><td><?php echo $COL26; ?></td></tr>
	    <tr><td>COL27</td><td><?php echo $COL27; ?></td></tr>
	    <tr><td>COL28</td><td><?php echo $COL28; ?></td></tr>
	    <tr><td>COL29</td><td><?php echo $COL29; ?></td></tr>
	    <tr><td>COL30</td><td><?php echo $COL30; ?></td></tr>
	    <tr><td>COL31</td><td><?php echo $COL31; ?></td></tr>
	    <tr><td>COL32</td><td><?php echo $COL32; ?></td></tr>
	    <tr><td>COL33</td><td><?php echo $COL33; ?></td></tr>
	    <tr><td>COL34</td><td><?php echo $COL34; ?></td></tr>
	    <tr><td>COL35</td><td><?php echo $COL35; ?></td></tr>
	    <tr><td>COL36</td><td><?php echo $COL36; ?></td></tr>
	    <tr><td>COL37</td><td><?php echo $COL37; ?></td></tr>
	    <tr><td>COL38</td><td><?php echo $COL38; ?></td></tr>
	    <tr><td>COL39</td><td><?php echo $COL39; ?></td></tr>
	    <tr><td>COL40</td><td><?php echo $COL40; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('simda') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file simda/simda_read */
/* Location: ./application/views/simda/simda_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-18 21:02:06 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 18 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
