<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Simda List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>COL1</th>
		<th>COL2</th>
		<th>COL3</th>
		<th>COL4</th>
		<th>COL5</th>
		<th>COL6</th>
		<th>COL7</th>
		<th>COL8</th>
		<th>COL9</th>
		<th>COL10</th>
		<th>COL11</th>
		<th>COL12</th>
		<th>COL13</th>
		<th>COL14</th>
		<th>COL15</th>
		<th>COL16</th>
		<th>COL17</th>
		<th>COL18</th>
		<th>COL19</th>
		<th>COL20</th>
		<th>COL21</th>
		<th>COL22</th>
		<th>COL23</th>
		<th>COL24</th>
		<th>COL25</th>
		<th>COL26</th>
		<th>COL27</th>
		<th>COL28</th>
		<th>COL29</th>
		<th>COL30</th>
		<th>COL31</th>
		<th>COL32</th>
		<th>COL33</th>
		<th>COL34</th>
		<th>COL35</th>
		<th>COL36</th>
		<th>COL37</th>
		<th>COL38</th>
		<th>COL39</th>
		<th>COL40</th>
		
            </tr><?php
            foreach ($simda_data as $simda)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $simda->COL1 ?></td>
		      <td><?php echo $simda->COL2 ?></td>
		      <td><?php echo $simda->COL3 ?></td>
		      <td><?php echo $simda->COL4 ?></td>
		      <td><?php echo $simda->COL5 ?></td>
		      <td><?php echo $simda->COL6 ?></td>
		      <td><?php echo $simda->COL7 ?></td>
		      <td><?php echo $simda->COL8 ?></td>
		      <td><?php echo $simda->COL9 ?></td>
		      <td><?php echo $simda->COL10 ?></td>
		      <td><?php echo $simda->COL11 ?></td>
		      <td><?php echo $simda->COL12 ?></td>
		      <td><?php echo $simda->COL13 ?></td>
		      <td><?php echo $simda->COL14 ?></td>
		      <td><?php echo $simda->COL15 ?></td>
		      <td><?php echo $simda->COL16 ?></td>
		      <td><?php echo $simda->COL17 ?></td>
		      <td><?php echo $simda->COL18 ?></td>
		      <td><?php echo $simda->COL19 ?></td>
		      <td><?php echo $simda->COL20 ?></td>
		      <td><?php echo $simda->COL21 ?></td>
		      <td><?php echo $simda->COL22 ?></td>
		      <td><?php echo $simda->COL23 ?></td>
		      <td><?php echo $simda->COL24 ?></td>
		      <td><?php echo $simda->COL25 ?></td>
		      <td><?php echo $simda->COL26 ?></td>
		      <td><?php echo $simda->COL27 ?></td>
		      <td><?php echo $simda->COL28 ?></td>
		      <td><?php echo $simda->COL29 ?></td>
		      <td><?php echo $simda->COL30 ?></td>
		      <td><?php echo $simda->COL31 ?></td>
		      <td><?php echo $simda->COL32 ?></td>
		      <td><?php echo $simda->COL33 ?></td>
		      <td><?php echo $simda->COL34 ?></td>
		      <td><?php echo $simda->COL35 ?></td>
		      <td><?php echo $simda->COL36 ?></td>
		      <td><?php echo $simda->COL37 ?></td>
		      <td><?php echo $simda->COL38 ?></td>
		      <td><?php echo $simda->COL39 ?></td>
		      <td><?php echo $simda->COL40 ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file simda/simda_doc */
/* Location: ./application/views/simda/simda_doc */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-18 04:55:12 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 18 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
