<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Paket_detail Read</h2>
        <table class="table">
	    <tr><td>KdPaket</td><td><?php echo $kdPaket; ?></td></tr>
	    <tr><td>KdPekerjaan</td><td><?php echo $kdPekerjaan; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('paket_detail') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file paket_detail/paket_detail_read */
/* Location: ./application/views/paket_detail/paket_detail_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:22:32 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
