<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_jaminan_model extends CI_Model
{

    public $table = 'data_jaminan';
    public $id = 'kdJaminan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdJaminan,penjamin,nilai,tgl,Type,kdpaket');
        $this->datatables->from('data_jaminan');
        //add this line for join
        //$this->datatables->join('table2', 'data_jaminan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_jaminan/read/$1'),'Read')." | ".anchor(site_url('data_jaminan/update/$1'),'Update')." | ".anchor(site_url('data_jaminan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdJaminan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdJaminan', $q);
	$this->db->or_like('penjamin', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('Type', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdJaminan', $q);
	$this->db->or_like('penjamin', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('Type', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Data_jaminan_model.php */
/* Location: ./application/models/Data_jaminan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:46:14 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

