<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_pejabat_model extends CI_Model
{

    public $table = 'data_pejabat';
    public $id = 'kdpaket';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kpa,nipkpa,pptk,nippptk,pengawas,nippengawas,kdpaket');
        $this->datatables->from('data_pejabat');
        //add this line for join
        //$this->datatables->join('table2', 'data_pejabat.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_pejabat/read/$1'),'Read')." | ".anchor(site_url('data_pejabat/update/$1'),'Update')." | ".anchor(site_url('data_pejabat/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kpa');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_nama_by_id($id){
        $this->db->where('id_peg', $id);
        return $this->db->get('master_pegawai')->row('nama');
    }
    function get_nip_by_id($id){
        $this->db->where('id_peg', $id);
        return $this->db->get('master_pegawai')->row('nip');
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kpa', $q);
	$this->db->or_like('nipkpa', $q);
	$this->db->or_like('pptk', $q);
	$this->db->or_like('nippptk', $q);
	$this->db->or_like('pengawas', $q);
	$this->db->or_like('nippengawas', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kpa', $q);
	$this->db->or_like('nipkpa', $q);
	$this->db->or_like('pptk', $q);
	$this->db->or_like('nippptk', $q);
	$this->db->or_like('pengawas', $q);
	$this->db->or_like('nippengawas', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Data_pejabat_model.php */
/* Location: ./application/models/Data_pejabat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 19:30:19 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

