<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_kontrak_model extends CI_Model
{

    public $table = 'data_kontrak';
    public $id = 'kdKontrak';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdKontrak,tglakhir,TglKontrak,NomorPHO,tglPHO,NomorFHO,tglFHO,nilaiKontrak,kdpaket');
        $this->datatables->from('data_kontrak');
        //add this line for join
        //$this->datatables->join('table2', 'data_kontrak.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data_kontrak/read/$1'),'Read')." | ".anchor(site_url('data_kontrak/update/$1'),'Update')." | ".anchor(site_url('data_kontrak/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdKontrak');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdKontrak', $q);
	$this->db->or_like('tglakhir', $q);
	$this->db->or_like('TglKontrak', $q);
	$this->db->or_like('NomorPHO', $q);
	$this->db->or_like('tglPHO', $q);
	$this->db->or_like('NomorFHO', $q);
	$this->db->or_like('tglFHO', $q);
	$this->db->or_like('nilaiKontrak', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdKontrak', $q);
	$this->db->or_like('tglakhir', $q);
	$this->db->or_like('TglKontrak', $q);
	$this->db->or_like('NomorPHO', $q);
	$this->db->or_like('tglPHO', $q);
	$this->db->or_like('NomorFHO', $q);
	$this->db->or_like('tglFHO', $q);
	$this->db->or_like('nilaiKontrak', $q);
	$this->db->or_like('kdpaket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    //// tampil semua kontrak berdasarkan id-paket (kdpaket)
    function get_by_idpaket($id)
    {
        $this->db->where('kdpaket', $id);
        return $this->db->get($this->table)->row();
    }

    //// tampil semua kontrak berdasarkan id-paket (kdpaket)
    function get_addendum_by_idkontrak($id)
    {
        $this->db->where('kdKontrak', $id);
        return $this->db->get('data_kontrak_addendum')->result_array();
    }

}






/* End of file Data_kontrak_model.php */
/* Location: ./application/models/Data_kontrak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:59:44 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

