<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_opd_model extends CI_Model
{

    public $table = 'm_opd';
    public $id = 'kdOPD';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdOPD,nmOPD,Alamat,Telpon');
        $this->datatables->from('m_opd');
        //add this line for join
        //$this->datatables->join('table2', 'm_opd.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('m_opd/read/$1'),'Read')." | ".anchor(site_url('m_opd/update/$1'),'Update')." | ".anchor(site_url('m_opd/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdOPD');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdOPD', $q);
	$this->db->or_like('nmOPD', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Telpon', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdOPD', $q);
	$this->db->or_like('nmOPD', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Telpon', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_opd_model.php */
/* Location: ./application/models/M_opd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-15 03:06:26 */
/* http://harviacode.com */