<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_dpa_model extends CI_Model
{

    public $table = 'master_dpa';
    public $id = 'kdDPA';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdDPA,kategori,tahun,Tanggal,pa_id,bendahara_id,ppk_id');
        $this->datatables->from('master_dpa');
        //add this line for join
        //$this->datatables->join('table2', 'master_dpa.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('master_dpa/read/$1'),'Read')." | ".anchor(site_url('master_dpa/update/$1'),'Update')." | ".anchor(site_url('master_dpa/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdDPA');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdDPA', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('pa_id', $q);
	$this->db->or_like('bendahara_id', $q);
	$this->db->or_like('ppk_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdDPA', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('Tanggal', $q);
	$this->db->or_like('pa_id', $q);
	$this->db->or_like('bendahara_id', $q);
	$this->db->or_like('ppk_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Master_dpa_model.php */
/* Location: ./application/models/Master_dpa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-04 00:01:36 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 04 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

