<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_kegiatan_model extends CI_Model
{

    public $table = 'master_kegiatan';
    public $id = 'kdKegiatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdKegiatan,nmKegiatan,kd_program');
        $this->datatables->from('master_kegiatan');
        //add this line for join
        //$this->datatables->join('table2', 'master_kegiatan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('master_kegiatan/read/$1'),'Read')." | ".anchor(site_url('master_kegiatan/update/$1'),'Update')." | ".anchor(site_url('master_kegiatan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdKegiatan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdKegiatan', $q);
	$this->db->or_like('nmKegiatan', $q);
	$this->db->or_like('kd_program', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdKegiatan', $q);
	$this->db->or_like('nmKegiatan', $q);
	$this->db->or_like('kd_program', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Master_kegiatan_model.php */
/* Location: ./application/models/Master_kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-17 00:58:01 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 17 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

