<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_pegawai_model extends CI_Model
{

    public $table = 'master_pegawai';
    public $id = 'id_peg';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_peg,nama,nip,jabatan,pendidikan,jurusan,pangkat,golongan,ruang,tempat,tanggal_lahir,tgl_aktif,status,date_update');
        $this->datatables->from('master_pegawai');
        //add this line for join
        //$this->datatables->join('table2', 'master_pegawai.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('master_pegawai/read/$1'),'Read')." | ".anchor(site_url('master_pegawai/update/$1'),'Update')." | ".anchor(site_url('master_pegawai/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_peg');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_peg', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('ruang', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('tgl_aktif', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('date_update', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_peg', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('golongan', $q);
	$this->db->or_like('ruang', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('tgl_aktif', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('date_update', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Master_pegawai_model.php */
/* Location: ./application/models/Master_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-20 21:38:38 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 20 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

