<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simda_model_tests extends CI_Model
{

    public $table = 'simda';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

  

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('COL1', $q);
	$this->db->or_like('COL2', $q);
	$this->db->or_like('COL3', $q);
	$this->db->or_like('COL4', $q);
	$this->db->or_like('COL5', $q);
	$this->db->or_like('COL6', $q);
	$this->db->or_like('COL7', $q);
	$this->db->or_like('COL8', $q);
	$this->db->or_like('COL9', $q);
	$this->db->or_like('COL10', $q);
	$this->db->or_like('COL11', $q);
	$this->db->or_like('COL12', $q);
	$this->db->or_like('COL13', $q);
	$this->db->or_like('COL14', $q);
	$this->db->or_like('COL15', $q);
	$this->db->or_like('COL16', $q);
	$this->db->or_like('COL17', $q);
	$this->db->or_like('COL18', $q);
	$this->db->or_like('COL19', $q);
	$this->db->or_like('COL20', $q);
	$this->db->or_like('COL21', $q);
	$this->db->or_like('COL22', $q);
	$this->db->or_like('COL23', $q);
	$this->db->or_like('COL24', $q);
	$this->db->or_like('COL25', $q);
	$this->db->or_like('COL26', $q);
	$this->db->or_like('COL27', $q);
	$this->db->or_like('COL28', $q);
	$this->db->or_like('COL29', $q);
	$this->db->or_like('COL30', $q);
	$this->db->or_like('COL31', $q);
	$this->db->or_like('COL32', $q);
	$this->db->or_like('COL33', $q);
	$this->db->or_like('COL34', $q);
	$this->db->or_like('COL35', $q);
	$this->db->or_like('COL36', $q);
	$this->db->or_like('COL37', $q);
	$this->db->or_like('COL38', $q);
	$this->db->or_like('COL39', $q);
	$this->db->or_like('COL40', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Simda_model_test.php */
/* Location: ./application/models/Simda_model_test.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-21 05:12:51 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 21 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

