<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbpaket_model extends CI_Model
{

    public $table = 'tbpaket';
    public $id = 'kdPaket';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('kdPaket,nmPaket,tahun,md5namatahun,bidang');
        $this->datatables->from('tbpaket');
        //add this line for join
        //$this->datatables->join('table2', 'tbpaket.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tbpaket/read/$1'),'Read')." | ".anchor(site_url('tbpaket/update/$1'),'Update')." | ".anchor(site_url('tbpaket/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdPaket');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdPaket', $q);
	$this->db->or_like('nmPaket', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('md5namatahun', $q);
	$this->db->or_like('bidang', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdPaket', $q);
	$this->db->or_like('nmPaket', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('md5namatahun', $q);
	$this->db->or_like('bidang', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}






/* End of file Tbpaket_model.php */
/* Location: ./application/models/Tbpaket_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:19:04 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/

