<!doctype html>
<html>
    <head>
        <title> <?= _APLIKASI_ ?> | MASTER_PROGRAM > <?php echo $button ?></title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Master_program <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    <div class="form-group">
            <label for="varchar">NmProgram <?php echo form_error('nmProgram') ?></label>
            <input type="text" class="form-control" name="nmProgram" id="nmProgram" placeholder="NmProgram" value="<?php echo $nmProgram; ?>" />
        </div>
	    <input type="hidden" name="kdProgram" value="<?php echo $kdProgram; ?>" /> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('master_program') ?>" class="btn btn-default">Cancel</a>
	</form>
    </body>
</html>




<?php
/* End of file master_program/master_program_form */
/* Location: ./application/view/master_program/master_program_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-17 00:57:38 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 17 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
