<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Master_program Read</h2>
        <table class="table">
	    <tr><td>NmProgram</td><td><?php echo $nmProgram; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('master_program') ?>" class="btn btn-default">Cancel</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file master_program/master_program_read */
/* Location: ./application/views/master_program/master_program_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-17 00:57:38 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 17 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
