<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            .word-table {
                border:1px solid black !important; 
                border-collapse: collapse !important;
                width: 100%;
            }
            .word-table tr th, .word-table tr td{
                border:1px solid black !important; 
                padding: 5px 10px;
            }
        </style>
    </head>
    <body>
        <h2>Tbuser List</h2>
        <table class="word-table" style="margin-bottom: 10px">
            <tr>
                <th>No</th>
		<th>Email</th>
		<th>Username</th>
		<th>Password</th>
		<th>Akses</th>
		<th>Bidang</th>
		<th>Status</th>
		
            </tr><?php
            foreach ($tbuser_data as $tbuser)
            {
                ?>
                <tr>
		      <td><?php echo ++$start ?></td>
		      <td><?php echo $tbuser->email ?></td>
		      <td><?php echo $tbuser->username ?></td>
		      <td><?php echo $tbuser->password ?></td>
		      <td><?php echo $tbuser->akses ?></td>
		      <td><?php echo $tbuser->bidang ?></td>
		      <td><?php echo $tbuser->status ?></td>	
                </tr>
                <?php
            }
            ?>
        </table>
    </body>
</html>




<?php
/* End of file tbuser/tbuser_doc */
/* Location: ./application/views/tbuser/tbuser_doc */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-15 09:14:14 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 15 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
