
        <h2 style="margin-top:0px">Data Jaminan <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
        <div class="form-group">
            <label for="set">Type <?php echo form_error('Type') ?></label>
            <!--input type="text" class="form-control" name="Type" id="Type" placeholder="Type" value="<?php echo $Type; ?>" /-->
            <select class="form-control" name="Type" id="Type" placeholder="Type" >
                <option value="<?php echo $Type; ?>"><?php echo $Type; ?></option>
                <option value="Jaminan Uang Muka">Jaminan Uang Muka</option>
                <option value="Jaminan Pelaksanaan">Jaminan Pelaksanaan</option>
                <option value="Jaminan Pemeliharaan">Jaminan Pemeliharaan</option>
            </select>
        </div>

        <div class="form-group">
            <label for="varchar">Penjamin <?php echo form_error('penjamin') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="penjamin" id="penjamin" placeholder="Penjamin" value="<?php echo $penjamin; ?>" />
        </div>

        <div class="form-group">
            <label for="double">Kode <?php echo form_error('kdJaminan') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="kdJaminan" id="kdJaminan" placeholder="Kode Jaminan" value="<?php echo $kdJaminan; ?>" /> 
        </div>
	    
	    <div class="form-group">
            <label for="double">Nilai <?php echo form_error('nilai') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="nilai" id="nilai" placeholder="Nilai" value="<?php echo $nilai; ?>" />
        </div>
	    <div class="form-group">
            <label for="date">Tgl <?php echo form_error('tgl') ?></label>
            <input type="text" class="form-control" autocomplete="off" name="tgl" id="datepicker"  placeholder="Tgl" value="<?php echo $tgl; ?>" />
        </div>
	   
	    <div class="form-group" style="display: none;">
            <?php $kdpaket = $this->uri->segment(3) ?>
            <label for="varchar">Id Paket <?php echo $kdpaket; ?><?php echo form_error('kdpaket') ?></label>
            <input type="hidden" class="form-control" autocomplete="off" name="kdpaket" id="kdpaket" placeholder="Kdpaket" value="<?php echo $kdpaket; ?>" />
        </div>
	   
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('paket/read/'.$kdpaket) ?>" class="btn btn-danger pull-right"><i class="fa fa-arrow-left"></i> Kembali</a>
	</form>
    




<?php
/* End of file data_jaminan/data_jaminan_form */
/* Location: ./application/view/data_jaminan/data_jaminan_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-19 17:46:14 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 19 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
