
    <!-- custom js '. data_rekanan .'-->
    <script src="<?php echo base_url('assets/datatables/jquery.dataTables.js') ?>"></script>
    <script src="<?php echo base_url('assets/datatables/dataTables.bootstrap.js') ?>"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $.fn.dataTableExt.oApi.fnPagingInfo = function(oSettings)
            {
                return {
                    "iStart": oSettings._iDisplayStart,
                    "iEnd": oSettings.fnDisplayEnd(),
                    "iLength": oSettings._iDisplayLength,
                    "iTotal": oSettings.fnRecordsTotal(),
                    "iFilteredTotal": oSettings.fnRecordsDisplay(),
                    "iPage": Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength),
                    "iTotalPages": Math.ceil(oSettings.fnRecordsDisplay() / oSettings._iDisplayLength)
                };
            };

            var t = $("#mytable").dataTable({
                initComplete: function() {
                    var api = this.api();
                    $('#mytable_filter input')
                            .off('.DT')
                            .on('keyup.DT', function(e) {
                                if (e.keyCode == 13) {
                                    api.search(this.value).draw();
                        }
                    });
                },
                oLanguage: {
                    //sProcessing: "loading..."
                    sProcessing: "</div><div class='overlay'>" +
                                        "<i class='fa fa-refresh fa-spin'></i>" +
                                    "</div>"
                },
                processing: true,
                serverSide: true,
                ajax: {"url": "data_rekanan/json", "type": "POST"},
                columns: [
                    {
                        "data": "id",
                        "orderable": false
                    },{"data": "Type"},{"data": "perusahaan"},{"data": "alamat"},{"data": "npwp"},{"data": "bank"},{"data": "rekening"},{"data": "direktur"},{"data": "jabatan"},{"data": "bentuk"},{"data": "kdpaket"},
                    {
                        "data" : "action",
                        "orderable": false,
                        "className" : "text-center"
                    }
                ],
                order: [[0, 'desc']],
                rowCallback: function(row, data, iDisplayIndex) {
                    var info = this.fnPagingInfo();
                    var page = info.iPage;
                    var length = info.iLength;
                    var index = page * length + (iDisplayIndex + 1);
                    $('td:eq(0)', row).html(index);
                }
            });
        });
    </script>

    <script type="text/javascript">
    function gantiType(perusahaan){
        ///// JIKA MENGUBAH JENIS PERUSAHAAN MAKA UBAH SINGKATAN JENIS PERUSAHAAN SAJA
        var text =perusahaan;
        if(perusahaan != ''){
            var spliText = perusahaan.split('.',2);
             if($.isArray(spliText) && spliText.length != 1){
                    text = spliText[1];
                    //console.error('spliText[1] 1' + $.isArray(spliText) + spliText.length );
            }else if($.isArray(spliText) && spliText[1] == ''){
                    text = spliText[1];
                    //console.error('spliText[1] 2');
            }else{
                    text = perusahaan;
                    //console.error('spliText[0] 3');
            }
        }
        return text;
    }

        // custom CODE HERE
        $('#Type').change(function(e) { 
            var per =$('#perusahaan');
            var pText = '';
            var a = $(this).children("option:selected").attr('data-text');
            var p = gantiType(per.val());
            $('#perusahaan').val(a+'. '+p);
            console.log(p);
            e.preventDefault();
            
        });

/// <?= $Type  ?> 

    </script>
    <!-- custom js m_opd-->
    




<?php
/* End of file data_rekanan/custom_js.php */
/* Location: ./application/view/data_rekanan/custom_js.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 05:02:21 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
