<!doctype html>
<html>
    <head>
        <title>harviacode.com - codeigniter crud generator</title>
        <link rel="stylesheet" href="<?php echo base_url('assets/bootstrap/css/bootstrap.min.css') ?>"/>
        <style>
            body{
                padding: 15px;
            }
        </style>
    </head>
    <body>
        <h2 style="margin-top:0px">Data_rekanan Read</h2>
        <table class="table">
	    <tr><td>Type</td><td><?php echo $Type; ?></td></tr>
	    <tr><td>Perusahaan</td><td><?php echo $perusahaan; ?></td></tr>
	    <tr><td>Alamat</td><td><?php echo $alamat; ?></td></tr>
	    <tr><td>Npwp</td><td><?php echo $npwp; ?></td></tr>
	    <tr><td>bank</td><td><?php echo $bank; ?></td></tr>
	    <tr><td>Rekening</td><td><?php echo $rekening; ?></td></tr>
	    <tr><td>Direktur</td><td><?php echo $direktur; ?></td></tr>
	    <tr><td>Bentuk</td><td><?php echo $bentuk; ?></td></tr>
	    <tr><td>Kdpaket</td><td><?php echo $kdpaket; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('paket/read/'.$kdpaket) ?>" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a></td></tr>
	</table>
        </body>
</html>




<?php
/* End of file data_rekanan/data_rekanan_read */
/* Location: ./application/views/data_rekanan/data_rekanan_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 05:02:21 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
