
<?php
$kdpaket = $this->uri->segment(3); 
?>
        <h2 style="margin-top:0px"></h2>
        <form action="<?php echo $action; ?>" method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="set">Type Perusahaan<?php echo form_error('Type') ?></label>
                    <select type="text" class="form-control" name="Type" id="Type" placeholder="Type" value="<?php echo $Type; ?>" />
                    <option value="<?php echo $Type; ?>"><?php echo $Type; ?></option>
                    <option value="1" data-text="CV" title="CV dengan kode 1">CV (Comanditaire Venotschap) #1</option>
                    <option value="2" data-text="PT" title="PT dengan kode 2">PT (Perseroan Terbatas) #2</option>
                    <option value="3" data-text="UD" title="UD dengan kode 3">UD (Usaha Dagang) #3</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="varchar">Perusahaan <?php echo form_error('perusahaan') ?></label>
                    <input type="text" class="form-control" name="perusahaan" id="perusahaan" placeholder="Perusahaan" value="<?php echo $perusahaan; ?>" />
                </div>
                <div class="form-group">
                    <label for="varchar">Nama Pimpinan <?php echo form_error('direktur') ?></label>
                    <input type="text" class="form-control" name="direktur" id="direktur" placeholder="Direktur" value="<?php echo $direktur; ?>" />
                </div>
                <div class="form-group">
                    <label for="varchar">Jabatan Pimpinan <?php echo form_error('jabatan') ?></label>
                    <input type="text" class="form-control" name="jabatan" id="direktur" placeholder="jabatan" value="<?php echo $jabatan; ?>" />
                </div>
                
                
            </div> 
            <div class="col-md-6">   
            <div class="form-group">
                    <label for="alamat"> <i class="fafa-map-pin"></i> Alamat <?php echo form_error('alamat') ?></label>
                    <textarea class="form-control" rows="1" name="alamat" id="alamat" placeholder="Alamat"><?php echo $alamat; ?></textarea>
                </div>
                <div class="form-group">
                    <label for="varchar">Nomor NPWP <?php echo form_error('npwp') ?></label>
                    <input type="text" class="form-control" name="npwp" id="npwp" placeholder="Npwp" value="<?php echo $npwp; ?>" />
                </div>
                
                <div class="form-group">
                    <label for="varchar">Nomor Rekening <?php echo form_error('rekening') ?></label>
                    <input type="text" class="form-control" name="rekening" id="rekening" placeholder="Rekening BANK" value="<?php echo $rekening; ?>" />
                </div>
                <div class="form-group">
                    <label for="varchar">Pada Bank <?php echo form_error('bank') ?></label>
                    <input type="text" class="form-control" name="bank" id="bank" placeholder="bank" value="<?php echo $bank; ?>" />
                </div>
               
                
            </div>  
            <hr>  
            
            <div class="col-md-12">
            <div class="form-group hide">
                    <label for="varchar">Bentuk <?php echo form_error('bentuk') ?></label>
                    <input type="hidden" class="form-control" name="bentuk" id="bentuk" placeholder="Bentuk" value="<?php echo $Type; ?>" />
                </div>
                <div class="form-group hide">
                    <label for="varchar">Kdpaket <?php echo form_error('kdpaket') ?></label>
                    <input type="hidden" class="form-control" name="kdpaket" id="kdpaket" placeholder="Kdpaket" value="<?php echo $kdpaket; ?>" />
                </div>
                <!--input type="hidden" name="id" value="<?php echo $id; ?>" /> 
                <button type="submit" class="btn btn-md btn-primary"><i class="fa fa-save"></i> <?php echo $button ?></button> 
                <a href="<?php echo site_url('paket/read/'.$kdpaket) ?>" class="btn btn-md btn-danger pull-right"><i class="fa fa-arrow-left"></i> Kembali</a-->
            </div>
            </div>
            <!--/form-->
            

<?php
/* End of file data_rekanan/data_rekanan_form */
/* Location: ./application/view/data_rekanan/data_rekanan_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-01 05:02:21 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 01 Feb 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
