
        <h2 style="margin-top:0px">Master_opd <?php echo $button ?></h2>
        <form action="<?php echo $action; ?>" method="post">
	    
        <div class="form-group">
            <label for="varchar">Pilih OPD <?php echo form_error('kdOPD') ?></label>
            <select type="text" class="form-control select2" name="kdOPD" id="kdOPD" placeholder="Pilih OPD" value="<?php echo $nmOPD; ?>" >
            <?php
                $this->db->group_by('COL39');
                $opd = $this->db->get('simda');
               foreach ($opd->result_array() as $op) {
                   echo ' 
                   <option value="'.$op['COL34'].'.'.$op['COL36'].'.'.$op['COL38'].'" title="'.$op['COL39'].'">'.$op['COL34'].$op['COL36'].$op['COL38'].' - '.$op['COL39'].'</option>
                   ';
               }
            ?>
            </select>
            <?php 
            // print_r($opd);
            ?>
        </div>
        <div class="form-group">
            <label for="varchar">Nama OPD <?php echo form_error('nmOPD') ?></label>
            <input type="text" class="form-control select2-setText" name="nmOPD" id="nmOPD" placeholder="NmOPD" value="<?php echo $nmOPD; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Alamat <?php echo form_error('Alamat') ?></label>
            <input type="text" class="form-control" name="Alamat" id="Alamat" placeholder="Alamat" value="<?php echo $Alamat; ?>" />
        </div>
	    <div class="form-group">
            <label for="varchar">Telpon <?php echo form_error('Telpon') ?></label>
            <input type="text" class="form-control" name="Telpon" id="Telpon" placeholder="Telpon" value="<?php echo $Telpon; ?>" />
        </div>
	    <input type="hidden" name="kdOPD-last" value="<?php echo $kdOPD; ?>"> 
	    <button type="submit" class="btn btn-primary"><?php echo $button ?></button> 
	    <a href="<?php echo site_url('master_opd') ?>" class="btn btn-default">Cancel</a>
	</form>
   



<?php
/* End of file master_opd/master_opd_form */
/* Location: ./application/view/master_opd/master_opd_form */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-20 18:04:46 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 20 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
