
        <h2 style="margin-top:0px">Detail OPD </h2>
        <table class="table">
	    <tr><td>NmOPD</td><td><?php echo $nmOPD; ?></td></tr>
	    <tr><td>Alamat</td><td><?php echo $Alamat; ?></td></tr>
	    <tr><td>Telpon</td><td><?php echo $Telpon; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('master_opd') ?>" class="btn btn-default">Kembali</a></td></tr>
	</table>
       

<?php
/* End of file master_opd/master_opd_read */
/* Location: ./application/views/master_opd/master_opd_read */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-20 18:04:46 */
/* http://harviacode.com */

/*============================================================================*/
/* Modify by Meedun 2020 */
/* version 1.4a */
/* Generated 20 Jan 2020 */
/*Template name : template/AdminLTE */
/*============================================================================*/
?>
